//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZOO_PROYECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int IdCita { get; set; }
        public int IdAnimCita { get; set; }
        public int IdVeteCita { get; set; }
        public System.DateTime FechaCita { get; set; }
        public System.TimeSpan HoraCita { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Veterinario Veterinario { get; set; }
    }
}
