//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZOO_PROYECT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZoologicoEntities : DbContext
    {
        public ZoologicoEntities()
            : base("name=ZoologicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<Cita> Cita { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Parqueadreo> Parqueadreo { get; set; }
        public virtual DbSet<ParqueadreoVehiculo> ParqueadreoVehiculo { get; set; }
        public virtual DbSet<Plans> Plans { get; set; }
        public virtual DbSet<PlansCliente> PlansCliente { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }
        public virtual DbSet<Veterinario> Veterinario { get; set; }
        public virtual DbSet<Zona> Zona { get; set; }
        public virtual DbSet<Zoologico> Zoologico { get; set; }
    }
}
