//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZOO_PROYECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parqueadreo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parqueadreo()
        {
            this.ParqueadreoVehiculo = new HashSet<ParqueadreoVehiculo>();
        }
    
        public int IdPar { get; set; }
        public int IdZooPar { get; set; }
        public string TelefonoPar { get; set; }
        public int ValorHora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParqueadreoVehiculo> ParqueadreoVehiculo { get; set; }
        public virtual Zoologico Zoologico { get; set; }
    }
}
