//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZOO_PROYECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlansCliente
    {
        public int IdPlansClie { get; set; }
        public int IdClie { get; set; }
        public int IdPlans { get; set; }
        public System.DateTime FechaPlansCliente { get; set; }
        public int NumPersonasPlansClie { get; set; }
        public int ValorPlansClie { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Plans Plans { get; set; }
    }
}
