//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZOO_PROYECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajador
    {
        public int IdTrab { get; set; }
        public int IdZona { get; set; }
        public string NombreTrab { get; set; }
        public string TelefonoTrab { get; set; }
        public string DireccionTrab { get; set; }
        public string CorreoTrab { get; set; }
        public string TipoSangreTrab { get; set; }
    
        public virtual Zona Zona { get; set; }
    }
}
